------------------ locally ------------------
DO $$
BEGIN
 -- Disable triggers and constraints
 EXECUTE 'ALTER TABLE match DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE tournament DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE player DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE team DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE "user" DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE request DISABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE prizecut DISABLE TRIGGER ALL';

 -- Truncate all tables
 EXECUTE 'TRUNCATE TABLE match CASCADE';
 EXECUTE 'TRUNCATE TABLE tournament CASCADE';
 EXECUTE 'TRUNCATE TABLE player CASCADE';
 EXECUTE 'TRUNCATE TABLE team CASCADE';
 EXECUTE 'TRUNCATE TABLE "user" CASCADE';
 EXECUTE 'TRUNCATE TABLE request CASCADE';
 EXECUTE 'TRUNCATE TABLE prizecut CASCADE';

 -- Re-enable triggers and constraints
 EXECUTE 'ALTER TABLE match ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE tournament ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE player ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE team ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE "user" ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE request ENABLE TRIGGER ALL';
 EXECUTE 'ALTER TABLE prizecut ENABLE TRIGGER ALL';
END $$;



------------------ public ------------------

DO $$
BEGIN
    TRUNCATE TABLE match, tournament, player, team, "user", request, prizecut CASCADE;

END $$;